version: '2'
services:
  web:
    build: ./
    image: 'topicquests/backside-servlet-ks'
    ports:
      - '8080:8080'
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
  elasticsearch:
    image: elasticsearch:2.4.1
